--TODO: CREATE STREAM BASED ON THE "stock_prices" KAFKA TOPIC, CALLED "STOCK_PRICES_STREAM" AND JSON VALUE FORMAT

--TODO CREATE STREAM BASED ON THE "stock_prices" KAFKA TOPIC, CALLED "STOCK_PRICES_TABLE", KEYED BY "STOCK_ID" AND JSON VALUE FORMAT

-- WARN: DO NOT MODIFY
CREATE STREAM STOCK_PRICES_STREAM_OUT WITH (
    KAFKA_TOPIC='stock_prices_stream', PARTITIONS=1
) AS SELECT * FROM STOCK_PRICES_STREAM;

CREATE TABLE STOCK_PRICES_TABLE_OUT WITH (
    KAFKA_TOPIC='stock_prices_table', PARTITIONS=1
) AS SELECT * FROM STOCK_PRICES_TABLE;