CREATE STREAM NEW_HIRES(ID BIGINT, COUNTRY VARCHAR, SALARY DOUBLE, DEPARTMENT VARCHAR) WITH (
    VALUE_FORMAT = 'AVRO', KAFKA_TOPIC = 'new_hires'
);

CREATE STREAM HIGH_SALARY_HIRES(ID BIGINT, COUNTRY VARCHAR, SALARY DOUBLE, DEPARTMENT VARCHAR) WITH (
    VALUE_FORMAT = 'JSON', KAFKA_TOPIC = 'high_salary_hires', PARTITIONS = 2
);

-- TODO: USE "INSERT AS SELECT" SYNTAX TO FILTER OUT NEW HIRES WITH SALARY LARGER THAN 30000.0 AND FEED THEM INTO THE "HIGH_SALARY_HIRES" STREAM AS DEFINED ABOVE
INSERT INTO HIGH_SALARY_HIRES SELECT * FROM NEW_HIRES WHERE SALARY > 30000.0;

--TODO: USE THE "CREATE AS SELECT" SYNTAX TO CREATE THE "MAX_SALARIES" TABLE, WHICH WOULD STORE, FOR EACH COUNTRY, ITS MAXIMAL SALARY AS "MAX_SALARY" AND STORE IT ON THE "max_salaries" TOPIC, IN THE "JSON" FORMAT
CREATE TABLE MAX_SALARIES WITH (
    KAFKA_TOPIC = 'max_salaries', PARTITIONS = 2, VALUE_FORMAT = 'JSON'
) AS SELECT MAX(SALARY) AS MAX_SALARY, COUNTRY FROM NEW_HIRES GROUP BY COUNTRY;