CREATE STREAM USER_EVENTS(USERID BIGINT, EVENT VARCHAR, DATA MAP<VARCHAR, VARCHAR>) WITH(
    KAFKA_TOPIC='user_events', VALUE_FORMAT='AVRO'
);

CREATE STREAM SERVICE_RECOMMENDATIONS(USERID BIGINT, MODEL VARCHAR, SERVICES ARRAY<BIGINT>) WITH(
    KAFKA_TOPIC = 'service_recommendations', VALUE_FORMAT='AVRO', KEY = 'MODEL'
);

-- TODO: CREATE THE 'USERS_INTERESTED_IN_INV' TABLE, WHICH WOULD STORE, IN 'DELIMTED' FORMAT, ON THE "users_interested"
-- TODO: TOPIC, ALL USERID'S FOR USERS WHO HAD AT LEAST 2 EVENTS OF TYPE 'CLICK' AND WITH "DATA" CONTAING THE "INVESTMENT"
-- TODO: AS "TARGET" IN THE "DATA" FIELD, DURING EACH 3 SECONDS (TUMBLING WINDOW)

-- TODO: RE-KEY THE DATA IN THE "service_recommendations" TOPIC TO PREPRE IT FOR THE JOIN WITH "USERS_INTERESTED_IN_INV"
-- TODO: AND STORE IT ON THE "recommendations_rekeyed" TOPIC

-- TODO: JOIN "USERS_INTERESTED_IN_INV" AND "RECOMMENDATIONS_REKEYED" TO PROVIDE A AN ARRAY OF RECOMMENDED SERVICES AS
-- TODO: "RECOMMNENDED_SERVICES" AND "USERID" IN A TABLE "USER_RECOMMENDATIONS" , STORED ON THE "user_recommendations"
-- TODO: TOPIC, IN 'AVRO' STORAGE FORMAT

